### ISSUE TITLE
Support for variable length data elements (LLVAR and LLLVAR)

### ISSUE THREAD

**Issue by missilerider** [adefirmanf/iso8583#10]
It would be great to support variable length data elements such as PAN (LLVAR up to 19).

The detail is easy as stated on [https://en.wikipedia.org/wiki/ISO_8583](https://en.wikipedia.org/wiki/ISO_8583).

Affected DE would be (at least in my implementation): 2, 32, 34, 35, 44, 48, 55, 56 and 62 for Primary.

Best!

**Comment by adefirmanf** [comment]
Yap, actually this feature already implemented on my another personal projects. So, it's not bundled with the library itself. But I still don't have any time to implemented yet into library itself. Sorry. 

Hopefully we can implemented this feature on the next version soon. But if you want to contribute, feel free to PR then. 

Thanks!

**Comment by missilerider** [comment]
Don't worry, I understand it. Maybe I try an implementation myself and PR if it has quality enough.

Thanks for your great work!
